version: '3'
services: 
    nodeapp:
        build: .
        volumes: 
            - .:/friend-to-friend-messaging
        command: "npm run start"

    nginx:
        image: nginx:alpine
        volumes: 
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public:/friend-to-friend-messaging/static
        ports: 
            - "80:80"
        links:
            - nodeapp:nodeapp
