version: '3'
services: 
    client:
        build: ./client
        volumes: 
            - ./client:/client
            - ./client/node_modules
        command: "npm run start"

    server:
        build: ./server
        volumes: 
            - ./server:/server
            - ./server/node_modules

    nginx:
        image: nginx:alpine
        volumes: 
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - "80:80"
        links:
            - client:client
            - server:server
        depends_on: 
            - server
            - client
